version: '3.7'
services:
  # DATABASE SERVICES
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
      - 33060
  
  # REVERSE PROXY
  nginx:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=app:8000
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    networks:
      - frontnet

  # BACKEND SERVICES
  app:
    build: app
    volumes:
      - ./app:/home/app
    restart: always
    ports: 
      - '8000:8000'
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    environment:
      - IP_ADDR=${IP_ADDR}
      - HOST=${HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backnet
      - frontnet

volumes:
  db-data:
networks:
  backnet:
  frontnet: